server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/important?serverTimezone=Asia/Seoul
    username: important
    password: important
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl